# (PART\*) Generalized linear models in `R` {-}

# Learning objectives

**Summary:** A significant limitation of linear models is that they
cannot accommodate response variables that do not have a normal error
distribution. Most biological data do not follow the assumption of
normality. In this workshop, you will learn how to use **generalized**
linear models, which are important tools to overcome the distributional
assumptions of linear models. You will learn the major distributions
used depending on the nature of the response variables, the concept of
the link function, and how to verify assumptions of such models.

This workshop's learning objectives are to:

1. Distinguish generalized linear models from general linear models (including their equations!).
2. Identify situations for when the use of generalized linear models is appropriate.
3. Test assumptions for generalized linear models.
4. Implement and execute generalized linear models in binary, proportion and count data.
5. Validate, interprete and visualise results of generalized linear models.

# Preparing for the workshop

To prepare for this workshop, you must do the following steps:

Download the R script and data required for this workshop:

-    [R Script](http://qcbs.ca/wiki/_media/glmm_e.r)
-    [Mites](http://qcbs.ca/wiki/_media/mites.csv)
-    [Faramea](http://qcbs.ca/wiki/_media/faramea.csv)

We will be using the following packages:

-    [ggplot2](https://cran.r-project.org/package=ggplot2) 
-    [MASS](https://cran.r-project.org/package=MASS) 
-    [vcdExtra](https://cran.r-project.org/package=vcdExtra) 
-    [bbmle](https://cran.r-project.org/package=bbmle)
-    [DescTools](https://cran.r-project.org/package=DescTools)


You can install and load these packages with the code below:

```{r, echo = TRUE, eval = FALSE}
install.packages("ggplot2")
install.packages("MASS")
install.packages("vcdExtra")
install.packages("bbmle")
install.packages("DescTools")

library(ggplot2)
library(MASS)
library(vcdExtra)
library(bbmle)
library(DescTools)
```

This workshop will build up your knowledge on models along side with some of their important equations. *Do not run to the mountains!* This will be achieved progressively and you will feel proud of yourself after!