# (PART\*) Additional GLM resources {-}

# Summary

GLMs are a powerful statistical technique for data with non-normal distributions as binomial, abundance and proportion data. These models are, howerver, not without many challenges and do not always offer the perfect solution to problems in data distribution. 

In the next workshop, you will see general and generalized linear mixed models. These models allow to overcome a number of limitations associated with traditional linear models by modelling part of the variation with a random variable. In that workshop, you will learn when it is important to use a mixed effects model to analyze your data. We will walk you through the steps to conduct a linear mixed model analysis, check its assumptions, report results, and visually represent your model in R. 

# Additional resources

**Books**:

B. Bolker (2009) Ecological Models and Data in R. Princeton University Press.
A. Zuur et al. (2009) Mixed Effects Models and Extensions in Ecology with R. Springer.

**Articles** :

Harrison et al. (2018), PeerJ, DOI [10.7717/peerj.4794
](http://dx.doi.org/10.7717/peerj.4794)

**Websites**:

[GLMM for Ecologists](http://glmm.wikidot.com) A great website on GLMM with a Q&A section!
