<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 An example with general linear models | Workshop 6: Generalized linear models</title>
  <meta name="description" content="Generalized linear models in R" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 An example with general linear models | Workshop 6: Generalized linear models" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://github.com/qcbsRworkshops/" />
  <meta property="og:image" content="https://github.com/qcbsRworkshops/assets/images/logo/csbq_logo_accueil.png" />
  <meta property="og:description" content="Generalized linear models in R" />
  <meta name="github-repo" content="qcbsRworkshops/workshop06" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 An example with general linear models | Workshop 6: Generalized linear models" />
  
  <meta name="twitter:description" content="Generalized linear models in R" />
  <meta name="twitter:image" content="https://github.com/qcbsRworkshops/assets/images/logo/csbq_logo_accueil.png" />

<meta name="author" content="Developed and maintained by the contributors of the QCBS R Workshop Series" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="assets/images/favicon.ico" type="image/x-icon" />
<link rel="prev" href="reviewing-linear-models.html"/>
<link rel="next" href="the-distributions-of-biological-data.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="assets/qcbs-style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo"><a href="./"><img src="assets/images/csbq_logo_gray_accueil.png"></a></li>
<link rel="icon" type="image/png" href="assets/images/favicon.ico"/>

<li class="divider"></li>
<li class="part"><span><b>QCBS R Workshop Series</b></span></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#code-of-conduct"><i class="fa fa-check"></i><b>0.1</b> Code of conduct</a><ul>
<li class="chapter" data-level="0.1.1" data-path="index.html"><a href="index.html#expected-behaviour"><i class="fa fa-check"></i><b>0.1.1</b> Expected behaviour</a></li>
<li class="chapter" data-level="0.1.2" data-path="index.html"><a href="index.html#unacceptable-behaviour"><i class="fa fa-check"></i><b>0.1.2</b> Unacceptable behaviour</a></li>
</ul></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#contributors"><i class="fa fa-check"></i><b>0.2</b> Contributors</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#contributing"><i class="fa fa-check"></i><b>0.3</b> Contributing</a></li>
</ul></li>
<li class="part"><span><b>Generalized linear models in <code>R</code></b></span></li>
<li class="chapter" data-level="1" data-path="learning-objectives.html"><a href="learning-objectives.html"><i class="fa fa-check"></i><b>1</b> Learning objectives</a></li>
<li class="chapter" data-level="2" data-path="preparing-for-the-workshop.html"><a href="preparing-for-the-workshop.html"><i class="fa fa-check"></i><b>2</b> Preparing for the workshop</a></li>
<li class="chapter" data-level="3" data-path="reviewing-linear-models.html"><a href="reviewing-linear-models.html"><i class="fa fa-check"></i><b>3</b> Reviewing linear models</a><ul>
<li class="chapter" data-level="3.1" data-path="reviewing-linear-models.html"><a href="reviewing-linear-models.html#general-linear-models"><i class="fa fa-check"></i><b>3.1</b> General linear models</a><ul>
<li class="chapter" data-level="3.1.1" data-path="reviewing-linear-models.html"><a href="reviewing-linear-models.html#definition"><i class="fa fa-check"></i><b>3.1.1</b> Definition</a></li>
<li class="chapter" data-level="3.1.2" data-path="reviewing-linear-models.html"><a href="reviewing-linear-models.html#assumptions"><i class="fa fa-check"></i><b>3.1.2</b> Assumptions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="an-example-with-general-linear-models.html"><a href="an-example-with-general-linear-models.html"><i class="fa fa-check"></i><b>4</b> An example with general linear models</a></li>
<li class="chapter" data-level="5" data-path="the-distributions-of-biological-data.html"><a href="the-distributions-of-biological-data.html"><i class="fa fa-check"></i><b>5</b> The distributions of biological data</a></li>
<li class="part"><span><b>GLMs with binary data</b></span></li>
<li class="chapter" data-level="6" data-path="binomial-glms-bernouilli.html"><a href="binomial-glms-bernouilli.html"><i class="fa fa-check"></i><b>6</b> Binomial GLMs (Bernouilli)</a><ul>
<li class="chapter" data-level="6.1" data-path="binomial-glms-bernouilli.html"><a href="binomial-glms-bernouilli.html#the-link-function"><i class="fa fa-check"></i><b>6.1</b> The link function</a><ul>
<li class="chapter" data-level="6.1.1" data-path="binomial-glms-bernouilli.html"><a href="binomial-glms-bernouilli.html#challenge-1"><i class="fa fa-check"></i><b>6.1.1</b> Challenge 1</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="binomial-glms-bernouilli.html"><a href="binomial-glms-bernouilli.html#interpreting-the-output-of-a-logistic-regression"><i class="fa fa-check"></i><b>6.2</b> Interpreting the output of a logistic regression</a></li>
<li class="chapter" data-level="6.3" data-path="binomial-glms-bernouilli.html"><a href="binomial-glms-bernouilli.html#predictive-power-and-goodness-of-fit"><i class="fa fa-check"></i><b>6.3</b> Predictive power and goodness-of-fit</a><ul>
<li class="chapter" data-level="6.3.1" data-path="binomial-glms-bernouilli.html"><a href="binomial-glms-bernouilli.html#challenge-2"><i class="fa fa-check"></i><b>6.3.1</b> Challenge 2</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="binomial-glms-bernouilli.html"><a href="binomial-glms-bernouilli.html#plotting-results"><i class="fa fa-check"></i><b>6.4</b> Plotting results</a></li>
</ul></li>
<li class="part"><span><b>GLMs with proportion data</b></span></li>
<li class="chapter" data-level="7" data-path="binomial-glms.html"><a href="binomial-glms.html"><i class="fa fa-check"></i><b>7</b> Binomial GLMS</a></li>
<li class="part"><span><b>GLMs with count data</b></span></li>
<li class="chapter" data-level="8" data-path="what-can-we-do-with-count-data.html"><a href="what-can-we-do-with-count-data.html"><i class="fa fa-check"></i><b>8</b> What can we do with count data?</a></li>
<li class="chapter" data-level="9" data-path="poisson-glms.html"><a href="poisson-glms.html"><i class="fa fa-check"></i><b>9</b> Poisson GLMs</a><ul>
<li class="chapter" data-level="9.1" data-path="poisson-glms.html"><a href="poisson-glms.html#the-problem-of-overdispersion"><i class="fa fa-check"></i><b>9.1</b> The problem of overdispersion</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="quasi-poisson-glms.html"><a href="quasi-poisson-glms.html"><i class="fa fa-check"></i><b>10</b> Quasi-Poisson GLMs</a></li>
<li class="chapter" data-level="11" data-path="negative-binomial-glms.html"><a href="negative-binomial-glms.html"><i class="fa fa-check"></i><b>11</b> Negative binomial GLMs</a><ul>
<li class="chapter" data-level="11.1" data-path="negative-binomial-glms.html"><a href="negative-binomial-glms.html#plotting-the-final-glm-to-the-data"><i class="fa fa-check"></i><b>11.1</b> Plotting the final GLM to the data</a><ul>
<li class="chapter" data-level="11.1.1" data-path="negative-binomial-glms.html"><a href="negative-binomial-glms.html#challenge-3"><i class="fa fa-check"></i><b>11.1.1</b> Challenge 3</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="conclusion-on-glms-with-count-data.html"><a href="conclusion-on-glms-with-count-data.html"><i class="fa fa-check"></i><b>12</b> Conclusion on GLMs with count data</a></li>
<li class="part"><span><b>Other distributions</b></span></li>
<li class="chapter" data-level="13" data-path="other-distributions.html"><a href="other-distributions.html"><i class="fa fa-check"></i><b>13</b> Other distributions</a></li>
<li class="part"><span><b>Additional GLM resources</b></span></li>
<li class="chapter" data-level="14" data-path="summary.html"><a href="summary.html"><i class="fa fa-check"></i><b>14</b> Summary</a></li>
<li class="chapter" data-level="15" data-path="additional-resources.html"><a href="additional-resources.html"><i class="fa fa-check"></i><b>15</b> Additional resources</a></li>
<li class="chapter" data-level="16" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>16</b> References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/qcbsRworkshops" target="blank">QCBS R Workshop Series</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Workshop 6: Generalized linear models</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<!------------------------ Hero Image Container --------------------------> 

<head>
  <meta name="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=10.0,initial-scale=1.0">
  <script src="https://kit.fontawesome.com/6a26f47516.js"></script>
  <script src="assets/qcbs-hideOutput.js"></script>
  <link href="assets/qcbs-style.css" rel="stylesheet">
</head>



<div class="hero-image-container"> 
  <img class= "hero-image" src="assets/images/jean-philippe-delberghe-75xPHEQBmvA-unsplash_hero_image.jpg">
</div>
<div id="an-example-with-general-linear-models" class="section level1">
<h1><span class="header-section-number">Chapter 4</span> An example with general linear models</h1>
<p>Let us use our prior knowledge on general linear models to explore the relationship between variables within the <em>Oribatid mite dataset</em>.</p>
<p>Let us begin by loading this dataset into <code>R</code>:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="an-example-with-general-linear-models.html#cb2-1"></a><span class="co"># Use setwd() to set your working directory</span></span>
<span id="cb2-2"><a href="an-example-with-general-linear-models.html#cb2-2"></a></span>
<span id="cb2-3"><a href="an-example-with-general-linear-models.html#cb2-3"></a>mites &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&#39;data/mites.csv&#39;</span>, </span>
<span id="cb2-4"><a href="an-example-with-general-linear-models.html#cb2-4"></a>                  <span class="dt">stringsAsFactors =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<p>The dataset that you just loaded is a subset from the classic ‘Oribatid
mite dataset’, which has been used in numerous texts (e.g. Borcard,
Gillet &amp; Legendre, <em>Numerical Ecology with R</em>), and which is available
in the <code>vegan</code> library.</p>
<p>The Oribatid mite dataset has <strong>70 observations with moss and mite samples</strong> collected Station de Biologie des
Laurentides from the Université de Montréal, within the municipality of Saint-Hippolyte, Québec (Canada). Each sample includes <strong>5</strong> variables of <strong>environmental measurements</strong> and abundance for <em>Galumna</em> sp. for each site.</p>
<p>We can peek into the structure and the first six rows of the dataset using the <code>head()</code> and <code>str()</code> functions:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="an-example-with-general-linear-models.html#cb3-1"></a><span class="kw">head</span>(mites)</span></code></pre></div>
<pre><code>##   Galumna pa totalabund        prop SubsDens WatrCont Substrate Shrub    Topo
## 1       8  1        140 0.057142857    39.18   350.15   Sphagn1   Few Hummock
## 2       3  1        268 0.011194030    54.99   434.81    Litter   Few Hummock
## 3       1  1        186 0.005376344    46.07   371.72 Interface   Few Hummock
## 4       1  1        286 0.003496503    48.19   360.50   Sphagn1   Few Hummock
## 5       2  1        199 0.010050251    23.55   204.13   Sphagn1   Few Hummock
## 6       1  1        209 0.004784689    57.32   311.55   Sphagn1   Few Hummock</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="an-example-with-general-linear-models.html#cb5-1"></a><span class="kw">str</span>(mites)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    70 obs. of  9 variables:
##  $ Galumna   : int  8 3 1 1 2 1 1 1 2 5 ...
##  $ pa        : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ totalabund: int  140 268 186 286 199 209 162 126 123 166 ...
##  $ prop      : num  0.05714 0.01119 0.00538 0.0035 0.01005 ...
##  $ SubsDens  : num  39.2 55 46.1 48.2 23.6 ...
##  $ WatrCont  : num  350 435 372 360 204 ...
##  $ Substrate : Factor w/ 7 levels &quot;Barepeat&quot;,&quot;Interface&quot;,..: 4 3 2 4 4 4 4 2 3 4 ...
##  $ Shrub     : Factor w/ 3 levels &quot;Few&quot;,&quot;Many&quot;,&quot;None&quot;: 1 1 1 1 1 1 1 2 2 2 ...
##  $ Topo      : Factor w/ 2 levels &quot;Blanket&quot;,&quot;Hummock&quot;: 2 2 2 2 2 2 2 1 1 2 ...</code></pre>
<p>Our first glance into the dataset already allows us to separate potential response variables from potential predictors:</p>
<div class="split">
<div class="split-left">
<p>Response variables:</p>
<ol style="list-style-type: decimal">
<li>Occurrence: <code>pa</code></li>
<li>Abundance: <code>Galumna</code></li>
<li>Relative Frequency or Proportion: <code>prop</code></li>
</ol>
</div>
<div class="split-right">
<p>Predictive variables:</p>
<ol style="list-style-type: decimal">
<li>Substract Density: <code>SubsDens</code></li>
<li>Water Content: <code>WatrCont</code></li>
<li>Substrate: <code>Substrate</code></li>
<li>Shrubs Nearby: <code>Shrub</code></li>
<li>Topography: <code>Topo</code></li>
</ol>
</div>
</div>
<p>We can also already ellaborate an initial question: <em>Could the abundance, occurrence or proportion of Galumna sp. be predicted by environmental features?</em></p>
<p>To answer this question, we can think of a variety of functions:</p>
<div class="split">
<div class="split-left">
<p><span class="math inline">\(\text{Abundance} = f(\text{Water content}, \epsilon)\)</span></p>
<p><span class="math inline">\(\text{Proportion} = f(\text{Water content}, \epsilon)\)</span></p>
<p><span class="math inline">\(\text{Occurrence} = f(\text{Substrate}, \epsilon)\)</span></p>
<p><span class="math inline">\(\text{Abundance} = f(\text{Topography}, \epsilon)\)</span></p>
</div>
<div class="split-right">
<p><span class="math inline">\(\text{Occurrence} = f(\text{Shrubs Nearby}, \epsilon)\)</span></p>
<p><span class="math inline">\(\text{Relative Frequency} = f(\text{Topography}, \epsilon)\)</span></p>
<p><span class="math inline">\(\text{Occurrence} = f(\text{Substract Density}, \epsilon)\)</span></p>
<p><span class="math inline">\(\text{Abundance} = f(\text{Substrate}, \epsilon)\)</span>
]</p>
</div>
</div>
<p>Let us attempt to be more specific and ask <strong>wether <em>Galumna</em>’s community values (abundance, occurrence and relative frequency) vary as a function of water content</strong>.</p>
<p>We can begin by representing all three response variables against the predictor:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="an-example-with-general-linear-models.html#cb7-1"></a><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">3</span>), <span class="dt">cex =</span> <span class="fl">1.4</span>)</span>
<span id="cb7-2"><a href="an-example-with-general-linear-models.html#cb7-2"></a></span>
<span id="cb7-3"><a href="an-example-with-general-linear-models.html#cb7-3"></a><span class="kw">plot</span>(Galumna <span class="op">~</span><span class="st"> </span>WatrCont,</span>
<span id="cb7-4"><a href="an-example-with-general-linear-models.html#cb7-4"></a>     <span class="dt">data =</span> mites, </span>
<span id="cb7-5"><a href="an-example-with-general-linear-models.html#cb7-5"></a>     <span class="dt">xlab =</span> <span class="st">&#39;Water content&#39;</span>, </span>
<span id="cb7-6"><a href="an-example-with-general-linear-models.html#cb7-6"></a>     <span class="dt">ylab =</span> <span class="st">&#39;Abundance&#39;</span>)</span>
<span id="cb7-7"><a href="an-example-with-general-linear-models.html#cb7-7"></a></span>
<span id="cb7-8"><a href="an-example-with-general-linear-models.html#cb7-8"></a><span class="kw">boxplot</span>(WatrCont <span class="op">~</span><span class="st"> </span>pa,</span>
<span id="cb7-9"><a href="an-example-with-general-linear-models.html#cb7-9"></a>        <span class="dt">data =</span> mites, </span>
<span id="cb7-10"><a href="an-example-with-general-linear-models.html#cb7-10"></a>        <span class="dt">xlab=</span><span class="st">&#39;Presence/Absence&#39;</span>,</span>
<span id="cb7-11"><a href="an-example-with-general-linear-models.html#cb7-11"></a>        <span class="dt">ylab =</span> <span class="st">&#39;Water content&#39;</span>)</span>
<span id="cb7-12"><a href="an-example-with-general-linear-models.html#cb7-12"></a></span>
<span id="cb7-13"><a href="an-example-with-general-linear-models.html#cb7-13"></a><span class="kw">plot</span>(prop <span class="op">~</span><span class="st"> </span>WatrCont, </span>
<span id="cb7-14"><a href="an-example-with-general-linear-models.html#cb7-14"></a>     <span class="dt">data =</span> mites, </span>
<span id="cb7-15"><a href="an-example-with-general-linear-models.html#cb7-15"></a>     <span class="dt">xlab =</span> <span class="st">&#39;Water content&#39;</span>, </span>
<span id="cb7-16"><a href="an-example-with-general-linear-models.html#cb7-16"></a>     <span class="dt">ylab =</span> <span class="st">&#39;Proportion&#39;</span>)</span></code></pre></div>
<p><img src="book-en_files/figure-html/unnamed-chunk-7-1.png" width="1632" /></p>
<p>Indeed, <code>Galumna</code> seems to vary negatively as a function of <code>WatrCont</code>, <em>i</em>.<em>e</em>.
<em>Galumna</em> sp. seems to prefer dryer sites.</p>
<p>We can go step further and fit general linear models to test whether <code>Galumna</code>, <code>pa</code>, and/or <code>prop</code> vary as a function of <code>WatrCont</code></p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="an-example-with-general-linear-models.html#cb8-1"></a>lm.abund &lt;-<span class="st"> </span><span class="kw">lm</span>(Galumna <span class="op">~</span><span class="st"> </span>WatrCont, <span class="dt">data =</span> mites)</span>
<span id="cb8-2"><a href="an-example-with-general-linear-models.html#cb8-2"></a><span class="co">## summary(lm.abund)</span></span>
<span id="cb8-3"><a href="an-example-with-general-linear-models.html#cb8-3"></a></span>
<span id="cb8-4"><a href="an-example-with-general-linear-models.html#cb8-4"></a>lm.pa &lt;-<span class="st"> </span><span class="kw">lm</span>(pa <span class="op">~</span><span class="st"> </span>WatrCont, <span class="dt">data =</span> mites)</span>
<span id="cb8-5"><a href="an-example-with-general-linear-models.html#cb8-5"></a><span class="co">## summary(lm.pa)</span></span>
<span id="cb8-6"><a href="an-example-with-general-linear-models.html#cb8-6"></a></span>
<span id="cb8-7"><a href="an-example-with-general-linear-models.html#cb8-7"></a>lm.prop &lt;-<span class="st"> </span><span class="kw">lm</span>(prop <span class="op">~</span><span class="st"> </span>WatrCont, <span class="dt">data =</span> mites)</span>
<span id="cb8-8"><a href="an-example-with-general-linear-models.html#cb8-8"></a><span class="co">## summary(lm.prop)</span></span></code></pre></div>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="an-example-with-general-linear-models.html#cb9-1"></a><span class="co"># Extracting the Pr(&gt;|t|)</span></span>
<span id="cb9-2"><a href="an-example-with-general-linear-models.html#cb9-2"></a></span>
<span id="cb9-3"><a href="an-example-with-general-linear-models.html#cb9-3"></a><span class="kw">summary</span>(lm.abund)<span class="op">$</span>coefficients[, <span class="dv">4</span>]</span></code></pre></div>
<pre><code>##  (Intercept)     WatrCont 
## 3.981563e-08 1.206117e-05</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="an-example-with-general-linear-models.html#cb11-1"></a><span class="kw">summary</span>(lm.pa)<span class="op">$</span>coefficients[, <span class="dv">4</span>]</span></code></pre></div>
<pre><code>##  (Intercept)     WatrCont 
## 6.030252e-12 4.676755e-08</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="an-example-with-general-linear-models.html#cb13-1"></a><span class="kw">summary</span>(lm.prop)<span class="op">$</span>coefficients[, <span class="dv">4</span>]</span></code></pre></div>
<pre><code>##  (Intercept)     WatrCont 
## 4.977432e-08 1.665437e-05</code></pre>
<p>We can see a strong and significant relationship for all three models, concerning each one of the three response variables!</p>
<p>Nevertheless, we cannot forget the most important step: verifying if the assumptions for these general linear models have not been violated.</p>
<p>Let us begin by validating these models to make sure that we respect assumptions of linear models, starting with the abundance model.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="an-example-with-general-linear-models.html#cb15-1"></a><span class="kw">plot</span>(Galumna <span class="op">~</span><span class="st"> </span>WatrCont, <span class="dt">data =</span> mites)</span>
<span id="cb15-2"><a href="an-example-with-general-linear-models.html#cb15-2"></a><span class="kw">abline</span>(lm.abund)</span></code></pre></div>
<p><img src="book-en_files/figure-html/unnamed-chunk-10-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The model does not fit well. It predicts negative abundance values when
WatrCont exceeds 600, which does not make any sense. Also, the model
does poorly at predicting high abundance values at low values of
WatrCont.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="an-example-with-general-linear-models.html#cb16-1"></a><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>), <span class="dt">cex =</span> <span class="fl">1.4</span>)</span>
<span id="cb16-2"><a href="an-example-with-general-linear-models.html#cb16-2"></a><span class="kw">plot</span>(lm.abund)</span></code></pre></div>
<p><img src="book-en_files/figure-html/unnamed-chunk-11-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><img src="images/6_diagplots.jpeg" /></p>
<p>Diagnostic plots show that the data/model violate assumptions of
homogeneity of variance (the graph on the left shows that residuals are
larger at higher fitted values) and normality (the graph on the right
indicates that residuals are not distributed as expected from a normal
distribution, i.e. many points are far from predicted values given by
the dotted line). Therefore, we need to reject this model, and can’t
use it to conclude that Galumna abundance varies as a function of water
content. Looking at diagnostic plots for the presence-absence model and
the proportion model also indicate that these models are inappropriate:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="an-example-with-general-linear-models.html#cb17-1"></a><span class="co">#Proportion</span></span>
<span id="cb17-2"><a href="an-example-with-general-linear-models.html#cb17-2"></a><span class="kw">plot</span>(prop <span class="op">~</span><span class="st"> </span>WatrCont, <span class="dt">data =</span> mites)</span>
<span id="cb17-3"><a href="an-example-with-general-linear-models.html#cb17-3"></a><span class="kw">abline</span>(lm.prop)</span></code></pre></div>
<p><img src="book-en_files/figure-html/unnamed-chunk-12-1.png" width="672" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="an-example-with-general-linear-models.html#cb18-1"></a><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>), <span class="dt">cex =</span> <span class="fl">1.4</span>)</span>
<span id="cb18-2"><a href="an-example-with-general-linear-models.html#cb18-2"></a><span class="kw">plot</span>(lm.prop)</span></code></pre></div>
<p><img src="book-en_files/figure-html/unnamed-chunk-12-2.png" width="672" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="an-example-with-general-linear-models.html#cb19-1"></a><span class="co">#Présence/Absence</span></span>
<span id="cb19-2"><a href="an-example-with-general-linear-models.html#cb19-2"></a><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="dt">cex =</span> <span class="fl">1.4</span>)</span>
<span id="cb19-3"><a href="an-example-with-general-linear-models.html#cb19-3"></a><span class="kw">plot</span>(pa <span class="op">~</span><span class="st"> </span>WatrCont, <span class="dt">data =</span> mites)</span>
<span id="cb19-4"><a href="an-example-with-general-linear-models.html#cb19-4"></a><span class="kw">abline</span>(lm.pa)</span></code></pre></div>
<p><img src="book-en_files/figure-html/unnamed-chunk-12-3.png" width="672" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="an-example-with-general-linear-models.html#cb20-1"></a><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>), <span class="dt">cex =</span> <span class="fl">1.4</span>)</span>
<span id="cb20-2"><a href="an-example-with-general-linear-models.html#cb20-2"></a><span class="kw">plot</span>(lm.pa)</span></code></pre></div>
<p><img src="book-en_files/figure-html/unnamed-chunk-12-4.png" width="672" style="display: block; margin: auto;" /></p>
<p>It is quite common with biological datasets that assumptions of
homogeneity of variance (homoscedasticity) and normality are not met.
These two assumptions are the main problem with linear models, and the
main reason why we need generalized linear models. Lets revisit the
basic equation for a linear model to better understand where these
assumptions come from. The equation for a linear model is:</p>
<p>y<sub>i</sub> = β<sub>0</sub> + β<sub>1</sub>x<sub>i</sub> + ε<sub>i</sub>, where:</p>
<ul>
<li>y<sub>i</sub> is the predicted value for the response variable,</li>
<li>β<sub>0</sub> is the intercept of the regression line between y and x,</li>
<li>β<sub>1</sub> is the slope of the regression line between y and x,</li>
<li>x<sub>i</sub> is the value for the explanatory variable,</li>
<li>ε<sub>i</sub> are the residuals of the model, which are drawn from a normal
distribution with a varying mean but a constant variance.</li>
</ul>
<p>This last point about ε<sub>i</sub> is important. This is where assumptions of
normality and homoscedasticity originate. It means that the residuals
(the distance between each observation and the regression line) can be
predicted by drawing random values from a normal distribution. Recall
that all normal distributions have two parameters, μ (the mean of the
distribution) and σ<sup>2</sup> (the variance of the distribution):</p>
<p><img src="images/6_normal_params.jpeg" /></p>
<p>In a linear model, μ changes based on values of x (the predictor
variable), but σ<sup>2</sup> has the same value for all values of Y. Indeed,
another equation to represent linear models is:</p>
<p>y<sub>i</sub> ~ <em>N</em>(μ = β<sub>0</sub> + β<sub>1</sub>x<sub>i</sub>, σ<sup>2</sup>),</p>
<p>which literally means that any given observation (y<sub>i</sub>) is drawn from a
normal distribution with parameters μ (which depends on the value of
x<sub>i</sub>) and σ<sup>2</sup>.</p>
<p>Predict Galumna abundance at a water content = 300 using this equation
and the linear model that we fitted earlier. You will need values for
β<sub>0</sub> and β<sub>1</sub> (regression coefficients) and ε<sub>i</sub> (the deviation of
observed values from the regression line)</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="an-example-with-general-linear-models.html#cb21-1"></a><span class="kw">coef</span>(lm.abund)</span></code></pre></div>
<pre><code>##  (Intercept)     WatrCont 
##  3.439348672 -0.006044788</code></pre>
<p>This model predicts that for a water content value of, say, 300, we
should obtain a Galumna abundance of 1.63:</p>
<p>3.44 + (-0.006 x 300) = 1.63.</p>
<p>That is the expected abundance if there was no residual. To get our
predicted values, we need to add ε<sub>i</sub>. This is where we use the normal
distribution. For x = 300, our model predicts that ε<sub>i</sub> should follow a
normal distribution with mean = 1.63. We can find the σ<sup>2</sup> value for our
abundance model by extracting it from the model summary:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="an-example-with-general-linear-models.html#cb23-1"></a><span class="kw">summary</span>(lm.abund)<span class="op">$</span>sigma</span></code></pre></div>
<pre><code>## [1] 1.513531</code></pre>
<p>We find that sigma is roughly 1.51. We now have all the coefficients
that we need to model Galumna abundance. At a water content of 300,
residuals should follow a normal distribution with parameters μ = 1.63
and σ<sup>2</sup> = 1.51.</p>
<p>At a water content of 400, residuals ε<sub>i</sub> should follow a normal
distribution with parameters μ = 3.44 + (-0.006 x 400) = 1.02 and σ<sup>2</sup> =
1.51, etc. Each y<sub>i</sub> value is modeled using a different normal
distribution, with a mean that depends on x<sub>i</sub>. The variance of all of
those normal distributions (σ<sup>2</sup>), however, is the same. Function lm()
finds the optimal σ<sup>2</sup> value that minimizes the total residual sum of
square and uses it for all normal distributions used to model y.
Graphically, this looks like this:</p>
<p><img src="images/6_lm_assump.jpeg" /></p>
<p>The four normal distributions on this graph represent the probability of
observing a given Galumna abundance for 4 different water content
values. The mean of the normal distribution varies as a function of
water content (hence μ decreases with water content), but σ<sup>2</sup> is always
1.51 (i.e. the variance is homogeneous across all values of x). This
model is inappropriate for at least two reasons:</p>
<p>1. Values are on average farther from the regression line at low water
content values. That is, there is more residual variance around the
predicted values for low values of x, such that ε<sub>i</sub> varies as a
function of x, thus violating the assumption of homoscedasticity. It
makes no sense to use a constant value of σ<sup>2</sup>: the normal distributions
used to predict y at low values of x should ideally be wider (have a
larger σ<sup>2</sup>) than normal distributions used to predict y at large x
values, but linear models do not permit this.</p>
<p>2. It makes no sense to use a normal distribution to predict y based on
x. Our response variable is abundance, which can only take integer
values. Yet, at water content = 300, the abundance value that our model
predicts to be the most probable is 1.63! We know that the probability
of observing 1.63 individuals at water content = 300 is actually zero,
as is the probability of observing any fraction (non-integers). Our
predicted values should be modeled using a distribution that only
predicts integers, rather than a continuous distribution like the normal
distribution. This is a very common problem, as biological data often
follows one of the myriad other statistical distributions besides the
normal distribution.</p>
<p>Generalized linear models can solve these two problems. Keep reading!</p>

</div>
<hr>
<center> 
  <div class="footer">
      All the content of the workshop series is under a <a href="https://creativecommons.org/licenses/by-nc/2.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.
  </div>
</center>
            </section>

          </div>
        </div>
      </div>
<a href="reviewing-linear-models.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="the-distributions-of-biological-data.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
