<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapitre 5 GLM avec une distribution binomiale (Bernouilli) | Atelier 6: Modèles linéaires généralisés en R</title>
  <meta name="description" content="Modèles linéaires généralisés en R" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapitre 5 GLM avec une distribution binomiale (Bernouilli) | Atelier 6: Modèles linéaires généralisés en R" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://github.com/qcbsRworkshops/" />
  <meta property="og:image" content="https://github.com/qcbsRworkshops/assets/images/logo/csbq_logo_accueil.png" />
  <meta property="og:description" content="Modèles linéaires généralisés en R" />
  <meta name="github-repo" content="qcbsRworkshops/workshop06" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapitre 5 GLM avec une distribution binomiale (Bernouilli) | Atelier 6: Modèles linéaires généralisés en R" />
  
  <meta name="twitter:description" content="Modèles linéaires généralisés en R" />
  <meta name="twitter:image" content="https://github.com/qcbsRworkshops/assets/images/logo/csbq_logo_accueil.png" />

<meta name="author" content="Développé et entretenu par les contributeurs et les contributrices de la Série d’ateliers R du CSBQ." />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="assets/images/favicon.ico" type="image/x-icon" />
<link rel="prev" href="les-distributions-des-données-biologiques.html"/>
<link rel="next" href="glm-avec-une-distribution-binomiale.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="assets/qcbs-style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo"><a href="./"><img src="assets/images/csbq_logo_gray_accueil.png"></a></li>
<link rel="icon" type="image/png" href="assets/images/favicon.ico"/>

<li class="divider"></li>
<li class="part"><span><b>Série d’ateliers R du CSBQ</b></span></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Préface</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#code-de-conduite"><i class="fa fa-check"></i><b>0.1</b> Code de conduite</a><ul>
<li class="chapter" data-level="0.1.1" data-path="index.html"><a href="index.html#comportement-attendu"><i class="fa fa-check"></i><b>0.1.1</b> Comportement attendu</a></li>
<li class="chapter" data-level="0.1.2" data-path="index.html"><a href="index.html#comportements-inacceptables"><i class="fa fa-check"></i><b>0.1.2</b> Comportements inacceptables</a></li>
</ul></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#contributeurs-et-contributrices"><i class="fa fa-check"></i><b>0.2</b> Contributeurs et contributrices</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#contribuez-à-la-série"><i class="fa fa-check"></i><b>0.3</b> Contribuez à la série!</a></li>
</ul></li>
<li class="part"><span><b>Modèles linéaires généralisés en <code>R</code></b></span></li>
<li class="chapter" data-level="1" data-path="objectifs-dapprentissage.html"><a href="objectifs-dapprentissage.html"><i class="fa fa-check"></i><b>1</b> Objectifs d’apprentissage</a></li>
<li class="chapter" data-level="2" data-path="préparez-vous-pour-cet-atelier.html"><a href="préparez-vous-pour-cet-atelier.html"><i class="fa fa-check"></i><b>2</b> Préparez-vous pour cet atelier</a></li>
<li class="chapter" data-level="3" data-path="quel-est-lutilité-des-modèles-linéaires-généralisés.html"><a href="quel-est-lutilité-des-modèles-linéaires-généralisés.html"><i class="fa fa-check"></i><b>3</b> Quel est l’utilité des modèles linéaires généralisés?</a></li>
<li class="chapter" data-level="4" data-path="les-distributions-des-données-biologiques.html"><a href="les-distributions-des-données-biologiques.html"><i class="fa fa-check"></i><b>4</b> Les distributions des données biologiques</a></li>
<li class="part"><span><b>GLM avec des données binaires</b></span></li>
<li class="chapter" data-level="5" data-path="glm-avec-une-distribution-binomiale-bernouilli.html"><a href="glm-avec-une-distribution-binomiale-bernouilli.html"><i class="fa fa-check"></i><b>5</b> GLM avec une distribution binomiale (Bernouilli)</a><ul>
<li class="chapter" data-level="5.1" data-path="glm-avec-une-distribution-binomiale-bernouilli.html"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#la-fonction-de-lien"><i class="fa fa-check"></i><b>5.1</b> La fonction de lien</a><ul>
<li class="chapter" data-level="5.1.1" data-path="glm-avec-une-distribution-binomiale-bernouilli.html"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#défi-1"><i class="fa fa-check"></i><b>5.1.1</b> Défi 1</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="glm-avec-une-distribution-binomiale-bernouilli.html"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#interpréter-la-sortie-dune-régression-logistique"><i class="fa fa-check"></i><b>5.2</b> Interpréter la sortie d’une régression logistique</a></li>
<li class="chapter" data-level="5.3" data-path="glm-avec-une-distribution-binomiale-bernouilli.html"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#pouvoir-prédictif-et-validation-du-modèle"><i class="fa fa-check"></i><b>5.3</b> Pouvoir prédictif et validation du modèle</a><ul>
<li class="chapter" data-level="5.3.1" data-path="glm-avec-une-distribution-binomiale-bernouilli.html"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#défi-2"><i class="fa fa-check"></i><b>5.3.1</b> Défi 2</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="glm-avec-une-distribution-binomiale-bernouilli.html"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#représentation-graphique-des-résultats"><i class="fa fa-check"></i><b>5.4</b> Représentation graphique des résultats</a></li>
</ul></li>
<li class="part"><span><b>GLM avec des données de proportions</b></span></li>
<li class="chapter" data-level="6" data-path="glm-avec-une-distribution-binomiale.html"><a href="glm-avec-une-distribution-binomiale.html"><i class="fa fa-check"></i><b>6</b> GLM avec une distribution binomiale</a></li>
<li class="part"><span><b>GLM avec des données d’abondance</b></span></li>
<li class="chapter" data-level="7" data-path="que-faire-avec-des-données-dabondance.html"><a href="que-faire-avec-des-données-dabondance.html"><i class="fa fa-check"></i><b>7</b> Que faire avec des données d’abondance?</a></li>
<li class="chapter" data-level="8" data-path="glm-avec-une-distribution-de-poisson.html"><a href="glm-avec-une-distribution-de-poisson.html"><i class="fa fa-check"></i><b>8</b> GLM avec une distribution de Poisson</a><ul>
<li class="chapter" data-level="8.0.1" data-path="glm-avec-une-distribution-de-poisson.html"><a href="glm-avec-une-distribution-de-poisson.html#la-validation-du-modèle-et-le-problème-de-la-surdispersion"><i class="fa fa-check"></i><b>8.0.1</b> La validation du modèle et le problème de la surdispersion</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="glm-avec-une-distribution-quasi-poisson.html"><a href="glm-avec-une-distribution-quasi-poisson.html"><i class="fa fa-check"></i><b>9</b> GLM avec une distribution quasi-Poisson</a></li>
<li class="chapter" data-level="10" data-path="glm-avec-une-distribution-binomiale-négative.html"><a href="glm-avec-une-distribution-binomiale-négative.html"><i class="fa fa-check"></i><b>10</b> GLM avec une distribution binomiale négative</a><ul>
<li class="chapter" data-level="10.1" data-path="glm-avec-une-distribution-binomiale-négative.html"><a href="glm-avec-une-distribution-binomiale-négative.html#représentation-graphique-du-modèle-final"><i class="fa fa-check"></i><b>10.1</b> Représentation graphique du modèle final</a><ul>
<li class="chapter" data-level="10.1.1" data-path="glm-avec-une-distribution-binomiale-négative.html"><a href="glm-avec-une-distribution-binomiale-négative.html#défi-3"><i class="fa fa-check"></i><b>10.1.1</b> Défi 3</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="conclusion-sur-les-glm-avec-des-données-dabondance.html"><a href="conclusion-sur-les-glm-avec-des-données-dabondance.html"><i class="fa fa-check"></i><b>11</b> Conclusion sur les GLM avec des données d’abondance</a></li>
<li class="part"><span><b>Autres distributions</b></span></li>
<li class="chapter" data-level="12" data-path="autres-distributions.html"><a href="autres-distributions.html"><i class="fa fa-check"></i><b>12</b> Autres distributions</a></li>
<li class="part"><span><b>Considérations finales</b></span></li>
<li class="chapter" data-level="13" data-path="sommaire.html"><a href="sommaire.html"><i class="fa fa-check"></i><b>13</b> Sommaire</a></li>
<li class="chapter" data-level="14" data-path="ressources-additionnelles.html"><a href="ressources-additionnelles.html"><i class="fa fa-check"></i><b>14</b> Ressources additionnelles</a></li>
<li class="chapter" data-level="15" data-path="réferences.html"><a href="réferences.html"><i class="fa fa-check"></i><b>15</b> Réferences</a></li>
<li class="divider"></li>
<li><a href="https://github.com/qcbsRworkshops" target="blank">QCBS R Workshop Series</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Atelier 6: Modèles linéaires généralisés en <code>R</code></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<!------------------------ Hero Image Container --------------------------> 

<head>
  <meta name="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=10.0,initial-scale=1.0">
  <script src="https://kit.fontawesome.com/6a26f47516.js"></script>
  <script src="assets/qcbs-hideOutput.js"></script>
  <link href="assets/qcbs-style.css" rel="stylesheet">
</head>



<div class="hero-image-container"> 
  <img class= "hero-image" src="assets/images/jean-philippe-delberghe-75xPHEQBmvA-unsplash_hero_image.jpg">
</div>
<div id="glm-avec-une-distribution-binomiale-bernouilli" class="section level1">
<h1><span class="header-section-number">Chapitre 5</span> GLM avec une distribution binomiale (Bernouilli)</h1>
<p>Les variables binaires sont fréquentes en écologie : on observe un
phénomène X ou son «absence». Par exemple, on note souvent la présence
ou l’absence d’espèces lors d’études de terrain. Le but est
généralement de déterminer si la présence d’une espèce est influencée
par différentes variables environnementales. D’autres exemples courants
sont la présence/absence d’une maladie au sein d’une population
sauvage, l’observation/non-observation d’un comportement spécifique et
la survie/mort d’un individu. Un modèle de régression qui utilise une
variable binaire comme variable réponse est l’un de plusieurs modèles
linéaires généralisés (GLM) et est appelé régression logistique ou
modèle logit.</p>
<p>Dans R, la présence (ou succès, survie…) est habituellement codée par
un <code>1</code> et une absence (ou échec, mort…) par un <code>0</code>. On effectue une
régression logistique (ou n’importe quel GLM) à l’aide de la fonction
<code>glm()</code>. Cette fonction diffère un peu de la fonction de base <code>lm()</code>,
car elle permet de spécifier une distribution statistique autre que la
distribution normale. Nous avons déjà vu que les variables binaires ne
sont pas distribuées normalement (<em>i.e.</em> on observe un pic à 0 et un pic
à 1 et rien entre les deux). La dernière section a montré que la
distribution de Bernoulli est appropriée pour modéliser les variables
réponses binaires. La moyenne de cette distribution est représentée par
la probabilité <em>p</em> d’observer un résultat et la variance est calculée
par <em>p</em>*(1 - <em>p</em>). Le terme (1 - <em>p</em>) représente la probabilité de ne
<strong>pas</strong> observer un résultat. Dans R, on spécifie la distribution
statistique du modèle avec l’argument <code>family</code>. Pour la régression
logistique, on l’indique de la façon suivante : <code>family = 'binomial</code>’.
Rappelez-vous que la distribution de Bernoulli est un cas spécifique de
la distribution binomiale lorsque le nombre de répétitions est égal à 1:
R «comprend» qu’il faut utiliser une distribution de Bernoulli.</p>
<p>Lorsqu’on prédit la probabilité d’observer un phénomène Y qui est une
variable binaire, la valeur prédite doit se trouver entre 0 et 1 :
c’est l’étendue possible d’une probabilité ! Si on utilise un modèle
linéaire de base pour modéliser une variable binaire en fonction de
variables explicatives, il est fort possible qu’on obtienne des valeurs
prédites qui se retrouvent en dehors de l’intervalle [0,1], ce qui ne
fait aucun sens. L’exemple suivant va vous permettre de mieux
comprendre pourquoi un modèle linéaire traditionnel est inapproprié. La
prochaine sous-section va vous montrer comment éviter ce problème avec
une fonction de lien. Brièvement, une fonction de lien est utilisée pour
linéariser la relation entre les valeurs prédites d’un modèle et le
prédicteur linéaire (voir sous-section suivante).</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb31-1"></a>model.lm &lt;-<span class="st"> </span><span class="kw">lm</span>(pa <span class="op">~</span><span class="st"> </span>WatrCont <span class="op">+</span><span class="st"> </span>Topo, <span class="dt">data =</span> mites)</span>
<span id="cb31-2"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb31-2"></a><span class="kw">fitted</span>(model.lm)</span></code></pre></div>
<pre><code>##           1           2           3           4           5           6 
##  0.66647889  0.53692818  0.63347146  0.65064083  0.88992555  0.72554642 
##           7           8           9          10          11          12 
##  0.62243838  0.44918156  0.38197312  0.86452345  0.65216882  0.58115232 
##          13          14          15          16          17          18 
##  0.82937368  0.49091140  0.32085505  0.70975427  0.74788803  0.77927339 
##          19          20          21          22          23          24 
##  0.27006616  0.97936848  0.92066821  0.91783725  0.59213949  0.75609015 
##          25          26          27          28          29          30 
##  0.40830867  0.45469271  0.97998058  0.65973050  0.70784146  0.24024164 
##          31          32          33          34          35          36 
##  0.44598561  0.42241754  0.26475620  0.29565189  0.41782680  0.21776232 
##          37          38          39          40          41          42 
##  0.25508504  0.04877715 -0.20118869  0.24807651  0.14103573  0.26617933 
##          43          44          45          46          47          48 
## -0.03165263 -0.22623884  0.03336756  0.16659086  0.36168204  0.08179987 
##          49          50          51          52          53          54 
##  0.30060989  0.19286520  0.14544285 -0.04279283  0.22290395  0.04560953 
##          55          56          57          58          59          60 
##  0.17240580  0.04198285 -0.08121733  0.31664687 -0.14695674  0.14463181 
##          61          62          63          64          65          66 
## -0.10106464 -0.11390341  0.11942865  0.19182463  0.46870977  0.06957320 
##          67          68          69          70 
## -0.40803217 -0.04559318  0.46895461  0.41060630</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb33-1"></a><span class="co"># La fonction «fitted()» extrait les valeurs prédites de la</span></span>
<span id="cb33-2"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb33-2"></a><span class="co"># variable réponse du modèle linéaire.  Certaines valeurs</span></span>
<span id="cb33-3"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb33-3"></a><span class="co"># sont en-dessous de 0, ce qui ne fait pas de sens pour une</span></span>
<span id="cb33-4"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb33-4"></a><span class="co"># régression logistique.  Essayons le même modèle, mais avec</span></span>
<span id="cb33-5"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb33-5"></a><span class="co"># une distribution binomiale cette fois-ci.  Remarquez</span></span>
<span id="cb33-6"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb33-6"></a><span class="co"># l&#39;argument «family» pour spécifier la distribution.</span></span>
<span id="cb33-7"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb33-7"></a>model.glm &lt;-<span class="st"> </span><span class="kw">glm</span>(pa <span class="op">~</span><span class="st"> </span>WatrCont <span class="op">+</span><span class="st"> </span>Topo, <span class="dt">data =</span> mites, <span class="dt">family =</span> binomial)</span>
<span id="cb33-8"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb33-8"></a><span class="kw">fitted</span>(model.glm)</span></code></pre></div>
<pre><code>##            1            2            3            4            5            6 
## 0.7346594257 0.4206031345 0.6631394056 0.7015590344 0.9653549812 0.8359993456 
##            7            8            9           10           11           12 
## 0.6372174958 0.5611742138 0.3897035615 0.9554194818 0.9124133201 0.5341181089 
##           13           14           15           16           17           18 
## 0.9371232991 0.6630994614 0.2534848511 0.8123833970 0.8652527310 0.8987976705 
##           19           20           21           22           23           24 
## 0.1672936363 0.9859583431 0.9745439489 0.9738080708 0.5622303983 0.8748321042 
##           25           26           27           28           29           30 
## 0.4560079466 0.2368433083 0.9860456411 0.7208455080 0.8093521595 0.1286310583 
##           31           32           33           34           35           36 
## 0.2209673461 0.4923424344 0.1597888373 0.2074205123 0.4804923276 0.1047615219 
##           37           38           39           40           41           42 
## 0.1468234813 0.0200046339 0.0015397957 0.1379815251 0.0502950337 0.1617730592 
##           43           44           45           46           47           48 
## 0.0088128566 0.0011890438 0.0171102995 0.0645145152 0.3411366744 0.0279131027 
##           49           50           51           52           53           54 
## 0.2159692960 0.0829690298 0.0525153673 0.0078621097 0.1098500760 0.0193729227 
##           55           56           57           58           59           60 
## 0.0682372458 0.0186736500 0.0052993359 0.2453448032 0.0026936317 0.0520999273 
##           61           62           63           64           65           66 
## 0.0043209522 0.0037861341 0.0406398167 0.0821545812 0.2640115440 0.0246819529 
##           67           68           69           70 
## 0.0001818862 0.0076395774 0.2645034420 0.1644306746</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb35-1"></a><span class="co"># Toutes les valeurs sont comprises entre 0 et 1.</span></span></code></pre></div>
<div id="la-fonction-de-lien" class="section level2">
<h2><span class="header-section-number">5.1</span> La fonction de lien</h2>
<p>Afin d’éviter les biais reliés aux modèles linéaires de base, nous
avons besoin de spécifier deux choses : une distribution statistique
pour les résidus du modèle et une fonction de lien pour les valeurs
prédites par ce même modèle. Nous avons déjà vu la distribution de
Bernoulli dans la section précédente, alors nous passerons directement à
l’explication du rôle de la fonction de lien.</p>
<p>Pour un modèle de régression linéaire d’une variable réponse continue
distribuée normalement, l’équation suivante nous permet d’obtenir les
valeurs prédites de la variable réponse :</p>
<p><em>μ</em> = <em>Xβ</em></p>
<p>où <em>μ</em> est la valeur prédite de la réponse variable, <em>X</em> est la matrice
du modèle (<em>i.e.</em> ça représente les variables explicatives) et <em>β</em>
correspond aux paramètres estimés à partir des données (<em>i.e.</em>
l’intercept et la pente). Le terme <em>Xβ</em> est appelé le prédicteur
linéaire. En termes mathématiques, c’est le produit matriciel de la
matrice du modèle <em>X</em> et du vecteur des paramètres estimés <em>β</em>.
Regardons cela de plus près dans R :</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb36-1"></a><span class="co"># Chargez le jeu de données CO2 utilisé dans un atelier</span></span>
<span id="cb36-2"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb36-2"></a><span class="co"># précédent</span></span>
<span id="cb36-3"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb36-3"></a><span class="kw">data</span>(CO2)</span>
<span id="cb36-4"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb36-4"></a><span class="kw">head</span>(CO2)</span></code></pre></div>
<pre><code>##   Plant   Type  Treatment conc uptake
## 1   Qn1 Quebec nonchilled   95   16.0
## 2   Qn1 Quebec nonchilled  175   30.4
## 3   Qn1 Quebec nonchilled  250   34.8
## 4   Qn1 Quebec nonchilled  350   37.2
## 5   Qn1 Quebec nonchilled  500   35.3
## 6   Qn1 Quebec nonchilled  675   39.2</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb38-1"></a><span class="co"># Construisez un modèle linéaire de l&#39;absorption de CO2 en</span></span>
<span id="cb38-2"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb38-2"></a><span class="co"># fonction de la concentration ambiante de CO2.</span></span>
<span id="cb38-3"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb38-3"></a>model.CO2 &lt;-<span class="st"> </span><span class="kw">lm</span>(uptake <span class="op">~</span><span class="st"> </span>conc, <span class="dt">data =</span> CO2)</span>
<span id="cb38-4"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb38-4"></a><span class="co"># On extraie la matrice du modèle avec la fonction</span></span>
<span id="cb38-5"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb38-5"></a><span class="co"># model.matrix().</span></span>
<span id="cb38-6"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb38-6"></a>X &lt;-<span class="st"> </span><span class="kw">model.matrix</span>(model.CO2)</span>
<span id="cb38-7"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb38-7"></a><span class="co"># Les paramètres estimés sont extraits ainsi :</span></span>
<span id="cb38-8"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb38-8"></a>B &lt;-<span class="st"> </span>model.CO2<span class="op">$</span>coefficients</span>
<span id="cb38-9"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb38-9"></a><span class="co"># On multiple X et B pour obtenir le prédicteur linéaire.  Le</span></span>
<span id="cb38-10"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb38-10"></a><span class="co"># symbole «%*%» indique qu&#39;on veut effectuer le produit</span></span>
<span id="cb38-11"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb38-11"></a><span class="co"># matriciel.</span></span>
<span id="cb38-12"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb38-12"></a>XB &lt;-<span class="st"> </span>X <span class="op">%*%</span><span class="st"> </span>B</span>
<span id="cb38-13"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb38-13"></a><span class="co"># On compare les valeurs de XB aux valeurs obtenues avec la</span></span>
<span id="cb38-14"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb38-14"></a><span class="co"># fonction fitted().  Toutes les déclarations devraient être</span></span>
<span id="cb38-15"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb38-15"></a><span class="co"># vraies (i.e. TRUE).  On utilise la fonction round() pour</span></span>
<span id="cb38-16"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb38-16"></a><span class="co"># que tous les éléments aient cinq décimales.</span></span>
<span id="cb38-17"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb38-17"></a><span class="kw">round</span>(<span class="kw">fitted</span>(model.CO2), <span class="dt">digits =</span> <span class="dv">5</span>) <span class="op">==</span><span class="st"> </span><span class="kw">round</span>(XB, <span class="dt">digits =</span> <span class="dv">5</span>)</span></code></pre></div>
<pre><code>##    [,1]
## 1  TRUE
## 2  TRUE
## 3  TRUE
## 4  TRUE
## 5  TRUE
## 6  TRUE
## 7  TRUE
## 8  TRUE
## 9  TRUE
....</code></pre>
<p>Lorsqu’on crée un modèle linéaire simple avec une variable réponse
continue distribuée normalement, le prédicteur linéaire est égal aux
valeurs attendues de la variable réponse. Ceci n’est pas exact si la
variable réponse n’est pas distribuée normalement. Si c’est le cas, il
faut appliquer une transformation sur les valeurs prédites, <em>i.e.</em> une
fonction de lien. La fonction de lien peut être vue comme une
transformation des valeurs prédites pour obtenir une <strong>relation
linéaire</strong> entre celles-ci et le prédicteur linéaire :</p>
<p><em>g</em>(<em>μ</em>) = <em>Xβ</em></p>
<p>où <em>g</em>(<em>μ</em>) est la fonction de lien des valeurs prédites. Ceci permet
d’enlever la contrainte de distribution normale des résidus. Lorsque la
variable réponse est une variable binaire, la fonction de lien est la
fonction logit et est représentée par l’équation suivante :</p>
<p>logit(<em>μ</em>) = log (<em>μ</em> / 1-<em>μ</em>) = <em>Xβ</em></p>
<p>où <em>μ</em> représente les valeurs prédites (<em>i.e.</em> la probabilité que Y = 1,
car on observe la présence d’une espèce, d’une maladie, d’un succès
ou d’un autre événement). Le ratio <em>μ</em> / 1-<em>μ</em> représente la cote (odds
en anglais) qu’un événement se produise. Cela transforme les valeurs
prédite sur une échelle de 0 à l’infini. Par exemple, si on a une
probabilité de 0,8 d’observer une espèce X, la cote est donc de 4 : il
est 4 fois plus probable d’observer l’espèce que de ne pas l’observer
- 0.8/(1-0.8) = 4. La transformation log (on appelle maintenant ce ratio
le log odds) permet aux valeurs d’être distribuées de moins l’infini à
l’infini. Donc, la fonction de lien logit prend les valeurs prédites du
modèle et les transforme en une variable continue sans borne. Les
valeurs prédites peuvent ainsi être reliées à un prédicteur linéaire.
C’est pour cette raison qu’on appelle ce modèle un modèle <strong>linéaire</strong>
généralisé même si la relation entre la variable réponse et la variable
explicative ne ressemble pas nécessairement à une «ligne droite» !</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb40-1"></a><span class="co"># On construit un modèle de régression de la présence/absence</span></span>
<span id="cb40-2"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb40-2"></a><span class="co"># d&#39;une espèce de mite (Galumna sp.)  en fonction du contenu</span></span>
<span id="cb40-3"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb40-3"></a><span class="co"># en eau du sol et de la topographie.  On utilise la fonction</span></span>
<span id="cb40-4"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb40-4"></a><span class="co"># glm() et on spécifie l&#39;argument «family».</span></span>
<span id="cb40-5"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb40-5"></a>logit.reg &lt;-<span class="st"> </span><span class="kw">glm</span>(pa <span class="op">~</span><span class="st"> </span>WatrCont <span class="op">+</span><span class="st"> </span>Topo, <span class="dt">data =</span> mites, <span class="dt">family =</span> <span class="kw">binomial</span>(<span class="dt">link =</span> <span class="st">&quot;logit&quot;</span>))</span>
<span id="cb40-6"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb40-6"></a><span class="co"># La fonction de lien «logit» est la fonction par défaut pour</span></span>
<span id="cb40-7"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb40-7"></a><span class="co"># une régression logistique, ce qui signifie qu&#39;il n&#39;est pas</span></span>
<span id="cb40-8"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb40-8"></a><span class="co"># nécessaire de l&#39;indiquer avec l&#39;argument «family»:</span></span>
<span id="cb40-9"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb40-9"></a>logit.reg &lt;-<span class="st"> </span><span class="kw">glm</span>(pa <span class="op">~</span><span class="st"> </span>WatrCont <span class="op">+</span><span class="st"> </span>Topo, <span class="dt">data =</span> mites, <span class="dt">family =</span> binomial)</span>
<span id="cb40-10"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb40-10"></a><span class="kw">summary</span>(logit.reg)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = pa ~ WatrCont + Topo, family = binomial, data = mites)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.0387  -0.5589  -0.1594   0.4112   2.0252  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  4.464402   1.670622   2.672 0.007533 ** 
## WatrCont    -0.015813   0.004535  -3.487 0.000489 ***
## TopoHummock  2.090757   0.735348   2.843 0.004466 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 91.246  on 69  degrees of freedom
## Residual deviance: 48.762  on 67  degrees of freedom
## AIC: 54.762
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<div id="défi-1" class="section level3">
<h3><span class="header-section-number">5.1.1</span> Défi 1</h3>
<p>En utilisant le jeu de données <code>bacteria</code> (du paquet <code>MASS</code>), modélisez
la présence de <em>H. influenzae</em> en fonction du traitement (<code>trt</code>) et de
la semaine de test (<code>week</code>). Commencez avec un modèle complet et
réduisez-le jusqu’à obtenir le modèle le plus parcimonieux possible.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb42-1"></a><span class="kw">data</span>(bacteria)</span>
<span id="cb42-2"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb42-2"></a><span class="kw">str</span>(bacteria)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    220 obs. of  6 variables:
##  $ y   : Factor w/ 2 levels &quot;n&quot;,&quot;y&quot;: 2 2 2 2 2 2 1 2 2 2 ...
##  $ ap  : Factor w/ 2 levels &quot;a&quot;,&quot;p&quot;: 2 2 2 2 1 1 1 1 1 1 ...
##  $ hilo: Factor w/ 2 levels &quot;hi&quot;,&quot;lo&quot;: 1 1 1 1 1 1 1 1 2 2 ...
##  $ week: int  0 2 4 11 0 2 6 11 0 2 ...
##  $ ID  : Factor w/ 50 levels &quot;X01&quot;,&quot;X02&quot;,&quot;X03&quot;,..: 1 1 1 1 2 2 2 2 3 3 ...
##  $ trt : Factor w/ 3 levels &quot;placebo&quot;,&quot;drug&quot;,..: 1 1 1 1 3 3 3 3 2 2 ...</code></pre>
<p><strong>Solution</strong></p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb44-1"></a>model.bact1 &lt;-<span class="st"> </span><span class="kw">glm</span>(y <span class="op">~</span><span class="st"> </span>trt <span class="op">*</span><span class="st"> </span>week, <span class="dt">family =</span> <span class="kw">binomial</span>(<span class="st">&quot;logit&quot;</span>), </span>
<span id="cb44-2"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb44-2"></a>    <span class="dt">data =</span> bacteria)</span>
<span id="cb44-3"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb44-3"></a>model.bact2 &lt;-<span class="st"> </span><span class="kw">glm</span>(y <span class="op">~</span><span class="st"> </span>trt <span class="op">+</span><span class="st"> </span>week, <span class="dt">family =</span> <span class="kw">binomial</span>(<span class="st">&quot;logit&quot;</span>), </span>
<span id="cb44-4"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb44-4"></a>    <span class="dt">data =</span> bacteria)</span>
<span id="cb44-5"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb44-5"></a>model.bact3 &lt;-<span class="st"> </span><span class="kw">glm</span>(y <span class="op">~</span><span class="st"> </span>week, <span class="dt">family =</span> <span class="kw">binomial</span>(<span class="st">&quot;logit&quot;</span>), <span class="dt">data =</span> bacteria)</span>
<span id="cb44-6"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb44-6"></a><span class="kw">anova</span>(model.bact1, model.bact2, model.bact3, <span class="dt">test =</span> <span class="st">&quot;LRT&quot;</span>)</span></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model 1: y ~ trt * week
## Model 2: y ~ trt + week
## Model 3: y ~ week
##   Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)  
## 1       214     203.12                       
## 2       216     203.81 -2  -0.6854  0.70984  
## 3       218     210.91 -2  -7.1026  0.02869 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>En se basant sur ces résultats, on doit choisir le modèle 2
comme celui représentant le mieux le jeu de données.</p>
</div>
</div>
<div id="interpréter-la-sortie-dune-régression-logistique" class="section level2">
<h2><span class="header-section-number">5.2</span> Interpréter la sortie d’une régression logistique</h2>
<p>La sortie du modèle de régression logistique indique que les deux
variables explicatives (<code>WatrCont</code> et <code>Topo</code>) sont significatives, mais
comment interprète-on les coefficients estimés? Rappelez-vous que nous
avons effectué une transformation des valeurs prédites par le modèle
(<em>i.e.</em> la probabilité que Y = 1), alors il faut utiliser une fonction
inverse pour pouvoir interpréter correctement les résultats. On peut
utiliser la fonction exponentielle <code>exp</code> pour obtenir la cote de
probabilité pour chaque variable explicative.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb46-1"></a>logit.reg</span></code></pre></div>
<pre><code>## 
## Call:  glm(formula = pa ~ WatrCont + Topo, family = binomial, data = mites)
## 
## Coefficients:
## (Intercept)     WatrCont  TopoHummock  
##     4.46440     -0.01581      2.09076  
## 
## Degrees of Freedom: 69 Total (i.e. Null);  67 Residual
## Null Deviance:       91.25 
## Residual Deviance: 48.76     AIC: 54.76</code></pre>
<p>Pour obtenir les pentes, il faut utiliser la fonction exponentielle exp().
Ceci mettra les coefficients sur l’échelle des cotes. Mathématiquement,
ceci correspond à :<br />
<strong>exp(model coefficients) = exp(log(μ / (1 - μ)) = u / (1 - μ)</strong>.</p>
<p>C’est notre rapport de cotes !</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb48-1"></a><span class="kw">exp</span>(logit.reg<span class="op">$</span>coefficients[<span class="dv">2</span>])</span></code></pre></div>
<pre><code>##  WatrCont 
## 0.9843118</code></pre>
<p>Pour obtenir l’intervalle de confiance sur l’échelle des cotes :</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb50-1"></a><span class="kw">exp</span>(<span class="kw">confint</span>(logit.reg)[<span class="dv">2</span>, ])</span></code></pre></div>
<pre><code>##     2.5 %    97.5 % 
## 0.9741887 0.9919435</code></pre>
<p>Prenez note que la cote pour une variable explicative est calculée
lorsque les autres variables sont gardées constantes. La topographie a
une cote de 8.09. Ceci signifie que la probabilité d’observer <em>Galumna</em>
sp. est 8.09 fois plus vraisemblable lorsque la topographie est de type
<code>hummock</code> plutôt que <code>blanket</code>.</p>
<p>Lorsque la cote est inférieure à 1, l’interprétation est un peu plus
compliquée. Si c’est le case, il faut prendre la valeur inverse de la
cote (<em>i.e.</em> 1 divisé par la cote) pour faciliter l’interprétation.
L’interprétation revient à dire comment l’observation d’un phénomène
est <strong>MOINS</strong> probable. Pour le contenu en eau du sol, la cote est de
0.984. L’inverse est 1 / 0.984 = 1.0159. Ceci signifie que
l’augmentation d’une unité en contenu en eau diminue la vraisemblance
d’observer la présence de <em>Galumna</em> sp. de 1.0159. On peut aussi
l’exprimer en pourcentage en soustrayant 1 à cette valeur : (1.0159 -
1) * 100 = 1.59 %. Il est 1.59 % moins vraisemblable d’observer
<em>Galumna</em> sp. avec une augmentation d’une unité de contenu en eau. Pour
se convaincre qu’on fait la bonne interprétation, on peut représenter
graphiquement les résultats de la présence de <em>Galumna</em> sp. en fonction
du contenu en eau du sol. On voit qu’en moyenne la présence de
<em>Galumna</em> sp. est plus élevée lorsque le contenu en eau est faible.</p>
<p><img src="images/galumna_pa.png" width="400" /></p>
<p>Lorsqu’un paramètre estimé est entre 0 et 1 sur l’échelle des cotes,
la relation entre la variable réponse et la variable explicative est
négative. Si la valeur est supérieure à 1, cela indique une relation
positive entre les variables. Si l’intervalle de confiance inclut la
valeur 1, la relation entre les variables n’est pas significative.
Rappelez-vous qu’une valeur de 1 sur l’échelle des cotes signifie que
la probabilité d’observer un phénomène Y est la même que celle de ne
pas observer ce phénomène (<em>i.e.</em> quand p = 0.5, 0.5/(1-0.5) = 1).</p>
<p>Pour obtenir une probabilité au lieu d’une cote pour chaque variable
explicative, il faut utiliser la fonction logit inverse :</p>
<p>logit<sup>-1</sup> = 1/(1+1/exp(x))</p>
<p>où x est le paramètre à transformer de l’échelle log odds à l’échelle
de probabilité. Pour le modèle <code>logit.reg</code>, le paramètre estimé pour la
topographie est de 2.091 sur l’échelle log odds. Donc, la probabilité
est donnée par :</p>
<p>1/(1+1/exp(2.091)) = 0.89 ce qui équivaut à 1/(1+1/8.09). Rappelez-vous
que la valeur 8.09 est sur l’échelle des cotes. On a une probabilité de
0.89 d’observer <em>Galumna</em> sp. lorsque la topographie est de type
<code>hummock</code>.</p>
<p>Calculons cette valeur de cote sans utiliser la fonction exp():</p>
<p>On commence avec la valeur de cote pour la topographie du modèle logit.reg:<br />
<strong>µ/ (1 - µ) = 8.09</strong></p>
<p>On réarrange pour isoler µ :<br />
<strong>µ = 8.09(1 - µ) = 8.09 - 8.09µ</strong><br />
<strong>8.09µ + µ = 8.09</strong><br />
<strong>µ(8.09 + 1) = 8.09</strong><br />
<strong>µ = 8.09 / (8.09 + 1)</strong><br />
<strong>µ = 1 / (1 + (1 / 8.09)) = 0.89</strong></p>
<p>On obtient le même résultat sans utiliser la fonction logit inverse !</p>
</div>
<div id="pouvoir-prédictif-et-validation-du-modèle" class="section level2">
<h2><span class="header-section-number">5.3</span> Pouvoir prédictif et validation du modèle</h2>
<p>Une façon simple et intuitive d’estimer le pouvoir explicatif d’un GLM
est de comparer la déviance du modèle à celle d’un modèle nul. La
déviance peut être vue comme une généralisation du concept de la somme
des carrés résiduelle lorsque le modèle est estimé par maximisation de
la vraisemblance (<em>i.e.</em> la méthode par laquelle on estime les
paramètres d’un GLM). Ceci nous permet de calculer un pseudo-R<sup>2</sup>, une
statistique similaire au R<sup>2</sup> dans une régression des moindres carrés
(<em>i.e.</em> la méthode utilisée pour estimer les paramètres d’une
régression linéaire de base). Le modèle nul correspond à un modèle sans
variable explicative. Dans R, on l’indique de la façon suivante :
<code>null.model &lt;- glm(Response.variable ~ 1, family = binomial)</code>. La forme
générique pour calculer un pseudo-R<sup>2</sup> est :</p>
<p>Pseudo-R<sup>2</sup> = (déviance du modèle nul – déviance résiduelle) / déviance
résiduelle</p>
<p>où «déviance du modèle nul» est la déviance du modèle nul et
«déviance résiduelle» est la déviance résiduelle du modèle d’intérêt.
La différence est divisée par la déviance du modèle nul afin de
contraindre le pseudo-R<sup>2</sup> entre 0 et 1.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb52-1"></a><span class="co"># Les déviances résiduelle et nulle sont déjà enregistrées</span></span>
<span id="cb52-2"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb52-2"></a><span class="co"># dans un objet de type glm.</span></span>
<span id="cb52-3"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb52-3"></a><span class="kw">objects</span>(logit.reg)</span></code></pre></div>
<pre><code>##  [1] &quot;aic&quot;               &quot;boundary&quot;          &quot;call&quot;             
##  [4] &quot;coefficients&quot;      &quot;contrasts&quot;         &quot;control&quot;          
##  [7] &quot;converged&quot;         &quot;data&quot;              &quot;deviance&quot;         
## [10] &quot;df.null&quot;           &quot;df.residual&quot;       &quot;effects&quot;          
## [13] &quot;family&quot;            &quot;fitted.values&quot;     &quot;formula&quot;          
## [16] &quot;iter&quot;              &quot;linear.predictors&quot; &quot;method&quot;           
## [19] &quot;model&quot;             &quot;null.deviance&quot;     &quot;offset&quot;           
## [22] &quot;prior.weights&quot;     &quot;qr&quot;                &quot;R&quot;                
## [25] &quot;rank&quot;              &quot;residuals&quot;         &quot;terms&quot;            
## [28] &quot;weights&quot;           &quot;xlevels&quot;           &quot;y&quot;</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb54-1"></a>pseudoR2 &lt;-<span class="st"> </span>(logit.reg<span class="op">$</span>null.deviance <span class="op">-</span><span class="st"> </span>logit.reg<span class="op">$</span>deviance)<span class="op">/</span>logit.reg<span class="op">$</span>null.deviance</span>
<span id="cb54-2"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb54-2"></a>pseudoR2</span></code></pre></div>
<pre><code>## [1] 0.4655937</code></pre>
<p>Les variables explicatives du modèle expliquent 46.6% de la variabilité
de la variable réponse.</p>
<p>Un pseudo-R<sup>2</sup> de McFadden ajusté, qui pénalise pour le nombre de
prédicteurs, peut être calculé comme suit:</p>
<p><img src="images/McFadden.PNG" /></p>
<p>où <strong>K</strong> correspond au nombre supplémentaire de prédicteurs par rapport
au modèle nul.</p>
<p>La qualité d’ajustement des modèles de régression logistique peut être
exprimée par des variantes de statistiques pseudo-R<sup>2</sup>, telles que les
mesures de Maddala (1983) ou de Cragg et Uhler (1970).</p>
<p>Lorsqu’on parle de régressions logistiques, les valeurs faibles de <strong>R<sup>2</sup></strong>
sont courantes.</p>
<p>La fonction R <code>DescTools::PseudoR2()</code> permet de calculer plusieurs pseudo-R<sup>2</sup>. En spécifiant <code>which = all</code>, calculez toutes les statistiques en même temps.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb56-1"></a>logit.reg &lt;-<span class="st"> </span><span class="kw">glm</span>(pa <span class="op">~</span><span class="st"> </span>WatrCont <span class="op">+</span><span class="st"> </span>Topo, <span class="dt">data =</span> mites, <span class="dt">family =</span> <span class="kw">binomial</span>(<span class="dt">link =</span> <span class="st">&quot;logit&quot;</span>))</span>
<span id="cb56-2"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb56-2"></a>DescTools<span class="op">::</span><span class="kw">PseudoR2</span>(logit.reg, <span class="dt">which =</span> <span class="st">&quot;all&quot;</span>)</span></code></pre></div>
<pre><code>##        McFadden     McFaddenAdj        CoxSnell      Nagelkerke   AldrichNelson 
##       0.4655937       0.3998373       0.4549662       0.6245898       0.3776866 
## VeallZimmermann           Efron McKelveyZavoina            Tjur             AIC 
##       0.6674318       0.5024101       0.7064093       0.5114661      54.7623962 
##             BIC          logLik         logLik0              G2 
##      61.5078819     -24.3811981     -45.6229593      42.4835224</code></pre>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb58-1"></a>fit &lt;-<span class="st"> </span><span class="kw">Rsq</span>(<span class="dt">object =</span> logit.reg)</span>
<span id="cb58-2"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb58-2"></a><span class="kw">HLtest</span>(<span class="dt">object =</span> fit)</span>
<span id="cb58-3"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb58-3"></a><span class="co"># La valeur de p est de 0.9051814. Donc, on ne rejète pas</span></span>
<span id="cb58-4"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb58-4"></a><span class="co"># notre modèle.  L&#39;ajustement du modèle est bon.</span></span></code></pre></div>
<div id="défi-2" class="section level3">
<h3><span class="header-section-number">5.3.1</span> Défi 2</h3>
<p>Évaluez l’ajustement et le pouvoir prédictif du modèle <code>model.bact2</code>.
Comment pouvez-vous améliorer le pouvoir prédictif du modèle ?</p>
<p><strong>Solution</strong></p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb59-1"></a>null.d &lt;-<span class="st"> </span>model.bact2<span class="op">$</span>null.deviance</span>
<span id="cb59-2"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb59-2"></a>resid.d &lt;-<span class="st"> </span>model.bact2<span class="op">$</span>deviance</span>
<span id="cb59-3"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb59-3"></a>bact.pseudoR2 &lt;-<span class="st"> </span>(null.d <span class="op">-</span><span class="st"> </span>resid.d)<span class="op">/</span>null.d</span>
<span id="cb59-4"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb59-4"></a>bact.pseudoR2</span></code></pre></div>
<pre><code>## [1] 0.0624257</code></pre>
<p>C’est très faible!</p>
<p>Le pouvoir prédictif pourrait être augmenté en incluant plus de
variables explicatives.</p>
</div>
</div>
<div id="représentation-graphique-des-résultats" class="section level2">
<h2><span class="header-section-number">5.4</span> Représentation graphique des résultats</h2>
<p>Lorsque le modèle a été validé, il peut être utile de représenter les
résultats graphiquement afin de voir comment la variable est influencée
par les variables explicatives. Une façon de faire est de mettre à la
fois les valeurs observées et prédites de la variable réponse en
fonction d’une variable explicative sur un même graphique. Voici un
exemple avec le paquet <code>ggplot2</code>. Revoir <a href="r_workshop3">l’atelier 3</a>
pour plus d’informations sur ce paquet.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb61-1"></a><span class="kw">ggplot</span>(mites, <span class="kw">aes</span>(<span class="dt">x =</span> WatrCont, <span class="dt">y =</span> pa)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">stat_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;glm&quot;</span>, </span>
<span id="cb61-2"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb61-2"></a>    <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>) <span class="op">+</span><span class="st"> </span><span class="kw">xlab</span>(<span class="st">&quot;Water content&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb61-3"><a href="glm-avec-une-distribution-binomiale-bernouilli.html#cb61-3"></a><span class="st">    </span><span class="kw">ylab</span>(<span class="st">&quot;Probabilité de présence&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ggtitle</span>(<span class="st">&quot;Probabilité de présence de Galumna sp. en fonction du contenu en eau&quot;</span>)</span></code></pre></div>
<p><img src="book-fr_files/figure-html/unnamed-chunk-37-1.png" width="672" style="display: block; margin: auto;" /></p>

</div>
</div>



<hr>
<center> 
  <div class="footer">
      All the content of the workshop series is under a <a href="https://creativecommons.org/licenses/by-nc/2.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.
  </div>
</center>
            </section>

          </div>
        </div>
      </div>
<a href="les-distributions-des-données-biologiques.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="glm-avec-une-distribution-binomiale.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
